### ISSUE TITLE
Lovelace Card Mirror for HASP

### ISSUE THREAD

**Issue by IIAIronWolf** [HASwitchPlate/HASPone#118]
Would it be possible to create a lovelace card that mirrors what is currently being shown on the LCD of the HASP? This would make it so much easier to edit things on the HASP, as people wouldn't have to be starting at a box installed in their wall while making each change. It probably sounds easier to implement than it is, but this would be an awesome feature to have someday!

**Comment by aderusha** [comment]
Not really, unless someone wanted to write a full Nextion emulator in Python and have it render to web.  Pretty steep hill to climb for a closed-source solution like Nextion, I really don't see it happening.

Would be damn cool though!

I'm closing this, not because it's a bad idea, but because it simply can't happen :(
